services:
  segma-realtime-console:
    image: registry.gitlab.com/wavein/xinos-docker/segma-realtime-console:${VERSION:-latest}
    build:
      context: .
    environment:
      - OPENAI_API_KEY
      - FLOWISE_API_URL
      - FLOWISE_CHATFLOW_ID
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT:-3000}
    ports:
      - ${BACKEND_PORT:-3000}:8000
      - ${FRONTEND_PORT:-3005}:3000
